apiVersion: v1
kind: BuildConfig
metadata:
  name: spring-pipeline
  labels:
    app: spring
  annotations:
    pipeline.alpha.openshift.io/uses: '[{"name": "spring", "namespace": "", "kind": "DeploymentConfig"}]'
spec:
  triggers:
  - type: GitHub
    github:
      secret: secret101
  runPolicy: Serial
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
         node {
           stage('buildImage'){
             openshiftBuild(buildConfig: 'spring', showBuildLogs: 'true')
           }
           stage('deployApplication'){
             openshiftDeploy(deploymentConfig: 'spring')
           }
         }
