spring:
  application:
    name: spring-sample
    
logging:
  config: classpath:logback.xml

# lets listen on all ports to ensure we can be invoked from the pod IP
server:
  address: 0.0.0.0

management:
  address: 0.0.0.0
  security:
    enabled: false

endpoints:
  enabled: true
  health:
    enabled: true

security:
  basic:
    enabled: false

# - Actuator Info
info:
  app:
    name: spring-sample
    description: Sample springboot application
    version:  1.0.0
    runtime-config-type: desktop
    APPLICATION_NAME: spring-sample