apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/tme-oms-channels-integration/spring
          imagePullPolicy: Always
          name: spring
          ports:
            - containerPort: 8080
              protocol: TCP
