apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: 
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"spring:latest","namespace":"tme-oms-som"},"fieldPath":"spec.template.spec.containers[?(@.name==\"spring\")].image"}]
  labels:
    app: spring
    app.kubernetes.io/part-of: tekton-demo-app
  name: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/tme-oms-channels-integration/spring
          imagePullPolicy: Always
          name: spring
          ports:
            - containerPort: 8080
              protocol: TCP
