apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring
  name: spring
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: spring
